# Generated by Django 4.1.5 on 2023-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartvision",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
